### ISSUE TITLE
Please provide an example of apikeys.json

### ISSUE THREAD

**Issue by fede2cr** [kscottz/PythonFromSpace#2]
I tried by defining it as a variable inside the example but fails later on.

Can you please provide an example of the file?

**Comment by kscottz** [comment]
```
{
    "PLANET_API_KEY":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}
```

**Comment by kscottz** [comment]
If you would like an API key you need to register [here for non-profit access](https://www.planet.com/products/education-and-research/) and [here for API developer access](https://www.planet.com/products/developer-program/).
