### ISSUE TITLE
NDVI Example Missing

### ISSUE THREAD

**Issue by vansant** [kscottz/PythonFromSpace#4]
Katherine,

Awesome talk at PyCon 2K17. Noticed you used RGB instead of NDVI in your talk to look at greenest parks in Portland - this documentation has NDVI listed as the correct way to do this but the link does not currently work. For the open satellite data this would be cool to see!

Have you implemented this already (with the NIR capable satellite data)?

**Comment by danabauer** [comment]
Here's a notebook I created to walk you through calculating NDVI with a PlanetScope 4-band image: https://github.com/planetlabs/notebooks/blob/master/ndvi/ndvi_planetscope.ipynb

I'll add the link to Kat's notebook.

**Comment by danabauer** [comment]
Added the link
